#############################################################################
# Makefile for building: bin/debug/eviewer
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri Nov 23 21:05:18 2012
# Project:  eviewer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile eviewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.moc
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/statusbar.cpp \
		src/toolbar.cpp \
		src/menubar.cpp \
		src/infodock.cpp \
		src/groupfiltersdock.cpp \
		src/settingsdock.cpp \
		src/timeline.cpp \
		src/graph.cpp \
		src/source.cpp \
		src/timelinebar.cpp \
		src/metamodel.cpp \
		src/eventscollector.cpp \
		src/groupfilter.cpp \
		src/sourcerow.cpp \
		src/events.cpp \
		src/qcustomplot/qcustomplot.cpp \
		src/infowidget.cpp \
		src/row.cpp .moc/moc_mainwindow.cpp \
		.moc/moc_statusbar.cpp \
		.moc/moc_toolbar.cpp \
		.moc/moc_menubar.cpp \
		.moc/moc_infodock.cpp \
		.moc/moc_timeline.cpp \
		.moc/moc_source.cpp \
		.moc/moc_timelinebar.cpp \
		.moc/moc_metamodel.cpp \
		.moc/moc_eventscollector.cpp \
		.moc/moc_groupfilter.cpp \
		.moc/moc_sourcerow.cpp \
		.moc/moc_events.cpp \
		.moc/moc_qcustomplot.cpp \
		.moc/moc_infowidget.cpp \
		.moc/moc_row.cpp \
		.rcc/qrc_res.cpp
OBJECTS       = .obj/main.o \
		.obj/mainwindow.o \
		.obj/statusbar.o \
		.obj/toolbar.o \
		.obj/menubar.o \
		.obj/infodock.o \
		.obj/groupfiltersdock.o \
		.obj/settingsdock.o \
		.obj/timeline.o \
		.obj/graph.o \
		.obj/source.o \
		.obj/timelinebar.o \
		.obj/metamodel.o \
		.obj/eventscollector.o \
		.obj/groupfilter.o \
		.obj/sourcerow.o \
		.obj/events.o \
		.obj/qcustomplot.o \
		.obj/infowidget.o \
		.obj/row.o \
		.obj/moc_mainwindow.o \
		.obj/moc_statusbar.o \
		.obj/moc_toolbar.o \
		.obj/moc_menubar.o \
		.obj/moc_infodock.o \
		.obj/moc_timeline.o \
		.obj/moc_source.o \
		.obj/moc_timelinebar.o \
		.obj/moc_metamodel.o \
		.obj/moc_eventscollector.o \
		.obj/moc_groupfilter.o \
		.obj/moc_sourcerow.o \
		.obj/moc_events.o \
		.obj/moc_qcustomplot.o \
		.obj/moc_infowidget.o \
		.obj/moc_row.o \
		.obj/qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		eviewer.pro
QMAKE_TARGET  = eviewer
DESTDIR       = bin/debug/
TARGET        = bin/debug/eviewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/debug/ || $(MKDIR) bin/debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: eviewer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -o Makefile eviewer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile eviewer.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/eviewer1.0.0 || $(MKDIR) .obj/eviewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/eviewer1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/statusbar.h src/toolbar.h src/menubar.h src/infodock.h src/groupfiltersdock.h src/settingsdock.h src/timeline.h src/graph.h src/source.h src/timelinebar.h src/timeline.h src/metamodel.h src/eventscollector.h src/groupfilter.h src/sourcerow.h src/events.h src/qcustomplot/qcustomplot.h src/infowidget.h src/row.h .obj/eviewer1.0.0/ && $(COPY_FILE) --parents res.qrc .obj/eviewer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/statusbar.cpp src/toolbar.cpp src/menubar.cpp src/infodock.cpp src/groupfiltersdock.cpp src/settingsdock.cpp src/timeline.cpp src/graph.cpp src/source.cpp src/timelinebar.cpp src/metamodel.cpp src/eventscollector.cpp src/groupfilter.cpp src/sourcerow.cpp src/events.cpp src/qcustomplot/qcustomplot.cpp src/infowidget.cpp src/row.cpp .obj/eviewer1.0.0/ && (cd `dirname .obj/eviewer1.0.0` && $(TAR) eviewer1.0.0.tar eviewer1.0.0 && $(COMPRESS) eviewer1.0.0.tar) && $(MOVE) `dirname .obj/eviewer1.0.0`/eviewer1.0.0.tar.gz . && $(DEL_FILE) -r .obj/eviewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_mainwindow.cpp .moc/moc_statusbar.cpp .moc/moc_toolbar.cpp .moc/moc_menubar.cpp .moc/moc_infodock.cpp .moc/moc_timeline.cpp .moc/moc_source.cpp .moc/moc_timelinebar.cpp .moc/moc_timeline.cpp .moc/moc_metamodel.cpp .moc/moc_eventscollector.cpp .moc/moc_groupfilter.cpp .moc/moc_sourcerow.cpp .moc/moc_events.cpp .moc/moc_qcustomplot.cpp .moc/moc_infowidget.cpp .moc/moc_row.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_mainwindow.cpp .moc/moc_statusbar.cpp .moc/moc_toolbar.cpp .moc/moc_menubar.cpp .moc/moc_infodock.cpp .moc/moc_timeline.cpp .moc/moc_source.cpp .moc/moc_timelinebar.cpp .moc/moc_timeline.cpp .moc/moc_metamodel.cpp .moc/moc_eventscollector.cpp .moc/moc_groupfilter.cpp .moc/moc_sourcerow.cpp .moc/moc_events.cpp .moc/moc_qcustomplot.cpp .moc/moc_infowidget.cpp .moc/moc_row.cpp
.moc/moc_mainwindow.cpp: src/toolbar.h \
		src/statusbar.h \
		src/menubar.h \
		src/infodock.h \
		src/groupfiltersdock.h \
		src/settingsdock.h \
		src/timeline.h \
		src/source.h \
		src/graph.h \
		src/sourcerow.h \
		src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o .moc/moc_mainwindow.cpp

.moc/moc_statusbar.cpp: src/statusbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/statusbar.h -o .moc/moc_statusbar.cpp

.moc/moc_toolbar.cpp: src/toolbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/toolbar.h -o .moc/moc_toolbar.cpp

.moc/moc_menubar.cpp: src/menubar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/menubar.h -o .moc/moc_menubar.cpp

.moc/moc_infodock.cpp: src/infodock.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/infodock.h -o .moc/moc_infodock.cpp

.moc/moc_timeline.cpp: src/source.h \
		src/graph.h \
		src/sourcerow.h \
		src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/timeline.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/timeline.h -o .moc/moc_timeline.cpp

.moc/moc_source.cpp: src/source.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/source.h -o .moc/moc_source.cpp

.moc/moc_timelinebar.cpp: src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/timelinebar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/timelinebar.h -o .moc/moc_timelinebar.cpp

.moc/moc_timeline.cpp: src/source.h \
		src/graph.h \
		src/sourcerow.h \
		src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/timeline.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/timeline.h -o .moc/moc_timeline.cpp

.moc/moc_metamodel.cpp: src/metamodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/metamodel.h -o .moc/moc_metamodel.cpp

.moc/moc_eventscollector.cpp: src/metamodel.h \
		src/groupfilter.h \
		src/eventscollector.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/eventscollector.h -o .moc/moc_eventscollector.cpp

.moc/moc_groupfilter.cpp: src/groupfilter.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/groupfilter.h -o .moc/moc_groupfilter.cpp

.moc/moc_sourcerow.cpp: src/sourcerow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/sourcerow.h -o .moc/moc_sourcerow.cpp

.moc/moc_events.cpp: src/sourcerow.h \
		src/events.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/events.h -o .moc/moc_events.cpp

.moc/moc_qcustomplot.cpp: src/qcustomplot/qcustomplot.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/qcustomplot/qcustomplot.h -o .moc/moc_qcustomplot.cpp

.moc/moc_infowidget.cpp: src/infowidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/infowidget.h -o .moc/moc_infowidget.cpp

.moc/moc_row.cpp: src/row.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/row.h -o .moc/moc_row.cpp

compiler_rcc_make_all: .rcc/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_res.cpp
.rcc/qrc_res.cpp: res.qrc \
		icons/24x24/info.png \
		icons/24x24/search.png \
		icons/24x24/zoom_out.png \
		icons/24x24/settings.png \
		icons/24x24/zoom_in.png
	/usr/bin/rcc -name res res.qrc -o .rcc/qrc_res.cpp

compiler_image_collection_make_all: .ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

.obj/main.o: src/main.cpp src/mainwindow.h \
		src/toolbar.h \
		src/statusbar.h \
		src/menubar.h \
		src/infodock.h \
		src/groupfiltersdock.h \
		src/settingsdock.h \
		src/timeline.h \
		src/source.h \
		src/graph.h \
		src/sourcerow.h \
		src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/events.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/toolbar.h \
		src/statusbar.h \
		src/menubar.h \
		src/infodock.h \
		src/groupfiltersdock.h \
		src/settingsdock.h \
		src/timeline.h \
		src/source.h \
		src/graph.h \
		src/sourcerow.h \
		src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainwindow.o src/mainwindow.cpp

.obj/statusbar.o: src/statusbar.cpp src/statusbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/statusbar.o src/statusbar.cpp

.obj/toolbar.o: src/toolbar.cpp src/toolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/toolbar.o src/toolbar.cpp

.obj/menubar.o: src/menubar.cpp src/menubar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/menubar.o src/menubar.cpp

.obj/infodock.o: src/infodock.cpp src/infodock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/infodock.o src/infodock.cpp

.obj/groupfiltersdock.o: src/groupfiltersdock.cpp src/groupfiltersdock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/groupfiltersdock.o src/groupfiltersdock.cpp

.obj/settingsdock.o: src/settingsdock.cpp src/settingsdock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/settingsdock.o src/settingsdock.cpp

.obj/timeline.o: src/timeline.cpp src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/graph.h \
		src/sourcerow.h \
		src/timeline.h \
		src/source.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/timeline.o src/timeline.cpp

.obj/graph.o: src/graph.cpp src/graph.h \
		src/sourcerow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/graph.o src/graph.cpp

.obj/source.o: src/source.cpp src/source.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/source.o src/source.cpp

.obj/timelinebar.o: src/timelinebar.cpp src/timelinebar.h \
		src/infowidget.h \
		src/qcustomplot/qcustomplot.h \
		src/timeline.h \
		src/source.h \
		src/graph.h \
		src/sourcerow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/timelinebar.o src/timelinebar.cpp

.obj/metamodel.o: src/metamodel.cpp src/metamodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/metamodel.o src/metamodel.cpp

.obj/eventscollector.o: src/eventscollector.cpp src/eventscollector.h \
		src/metamodel.h \
		src/groupfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/eventscollector.o src/eventscollector.cpp

.obj/groupfilter.o: src/groupfilter.cpp src/groupfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/groupfilter.o src/groupfilter.cpp

.obj/sourcerow.o: src/sourcerow.cpp src/sourcerow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/sourcerow.o src/sourcerow.cpp

.obj/events.o: src/events.cpp src/events.h \
		src/sourcerow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/events.o src/events.cpp

.obj/qcustomplot.o: src/qcustomplot/qcustomplot.cpp src/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qcustomplot.o src/qcustomplot/qcustomplot.cpp

.obj/infowidget.o: src/infowidget.cpp src/infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/infowidget.o src/infowidget.cpp

.obj/row.o: src/row.cpp src/row.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/row.o src/row.cpp

.obj/moc_mainwindow.o: .moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainwindow.o .moc/moc_mainwindow.cpp

.obj/moc_statusbar.o: .moc/moc_statusbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_statusbar.o .moc/moc_statusbar.cpp

.obj/moc_toolbar.o: .moc/moc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_toolbar.o .moc/moc_toolbar.cpp

.obj/moc_menubar.o: .moc/moc_menubar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_menubar.o .moc/moc_menubar.cpp

.obj/moc_infodock.o: .moc/moc_infodock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_infodock.o .moc/moc_infodock.cpp

.obj/moc_timeline.o: .moc/moc_timeline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_timeline.o .moc/moc_timeline.cpp

.obj/moc_source.o: .moc/moc_source.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_source.o .moc/moc_source.cpp

.obj/moc_timelinebar.o: .moc/moc_timelinebar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_timelinebar.o .moc/moc_timelinebar.cpp

.obj/moc_metamodel.o: .moc/moc_metamodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_metamodel.o .moc/moc_metamodel.cpp

.obj/moc_eventscollector.o: .moc/moc_eventscollector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_eventscollector.o .moc/moc_eventscollector.cpp

.obj/moc_groupfilter.o: .moc/moc_groupfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_groupfilter.o .moc/moc_groupfilter.cpp

.obj/moc_sourcerow.o: .moc/moc_sourcerow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_sourcerow.o .moc/moc_sourcerow.cpp

.obj/moc_events.o: .moc/moc_events.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_events.o .moc/moc_events.cpp

.obj/moc_qcustomplot.o: .moc/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_qcustomplot.o .moc/moc_qcustomplot.cpp

.obj/moc_infowidget.o: .moc/moc_infowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_infowidget.o .moc/moc_infowidget.cpp

.obj/moc_row.o: .moc/moc_row.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_row.o .moc/moc_row.cpp

.obj/qrc_res.o: .rcc/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_res.o .rcc/qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

