#ifndef  _LOG_CODES_H_
#define  _LOG_CODES_H_

//LOG STRUCTURE FLAGS

//<type><len><timestamp><code>
#define LOG_STRUCT_A					0x0000

//<type><len><timestamp><code>[PPE_ID]
#define LOG_STRUCT_B					0x1000

//<type><len><timestamp><code>[PPE_ID][node_addr]
#define LOG_STRUCT_C					0x2000

//<type><len><timestamp><code>[PPE_ID][node_addr][app_id]
#define LOG_STRUCT_D					0x3000

//<type><len><timestamp><code>[PPE_ID][node_addr][app_id][agent_id]
#define LOG_STRUCT_E					0x4000

//<type><len><timestamp><code>[PPE_ID][node_addr][app_id][agent_id][agent_type]
#define LOG_STRUCT_F					0x5000

#define LOG_STRUCT_MASK					0xF000

//LOG INDICATOR FLAG
#define LOG_INDICATOR					0x0800
#define LOG_NO_INDICATOR				0x0000

//LOG PRIORITY FLAGS
#define LOG_PRIORITY_NONE				0x0000
#define LOG_PRIORITY_LOW				0x0200
#define LOG_PRIORITY_MEDIUM				0x0400
#define LOG_PRIORITY_HIGH				0x0600

//LOG LEVEL FLAGS
#define LOG_LEVEL_PC					0x0000
#define LOG_LEVEL_PPE					0x0040
#define LOG_LEVEL_PROXY					0x0080
#define LOG_LEVEL_MW					0x00C0
#define LOG_LEVEL_API					0x0100
#define LOG_LEVEL_AGENT					0x0140
#define LOG_LEVEL_RESERVED1				0x0180
#define LOG_LEVEL_RESERVED2				0x01C0

//-------------------------------------------------//

//LOG TYPES & CODES

//!!!PPE LEVEL
//TYPE
#define T_PORTPLEX_STATUS (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0000)
//CODES
#define E_PORTPLEX_STARTED              		0x00000001
#define E_PORTPLEX_KILLED               		0x00000002
#define E_PORTPLEX_PROXY_MANAGER_CONNECTED		0x00000003
#define E_PORTPLEX_PROXY_MANAGER_DISCONNECTED 	0x00000004
#define E_EXTERNAL_PORTPLEX_CONNECTED			0x00000005
#define E_CONNECTED_TO_EXTERNAL_PORTPLEX		0x00000006
#define E_PORTPLEX_PROXY_CONNECTED				0x00000007
#define E_PORTPLEX_PROXY_DISCONNECTED			0x00000008


//TYPE
#define T_PORTPLEX_ERROR (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_PPE | 0x0001)
//CODES

//TYPE
#define T_MUX_STATUS (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0002)
//CODES
#define E_MUX_STARTED                   0x00000001
#define E_MUX_KILLED                    0x00000002
#define E_SPN_CONNECTED                 0x00000003
#define E_SPN_DISCONNECTED              0x00000004
#define E_PROXY_MANAGER_CONNECTED       0x00000005
#define E_PROXY_MANAGER_DISCONNECTED    0x00000006

//TYPE
#define T_MUX_ERROR (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_PPE | 0x0003)
//CODES

//TYPE
#define T_PROXYMNGR_STATUS (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0004)
//CODES

//TYPE
#define T_PROXYMNGR_ERROR (LOG_STRUCT_B | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_PPE | 0x0005)
//CODES

//TYPE
#define T_PORTPLEX_PERF (LOG_STRUCT_B | LOG_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0006)
//CODES
#define P_PORTPLEX_TOTAL_TX_PER_SEC			0x00000001
#define P_PORTPLEX_TOTAL_RX_PER_SEC			0x00000002
#define P_PORTPLEX_EXTERNAL_TX_PER_SEC		0x00000003
#define P_PORTPLEX_EXTERNAL_RX_PER_SEC		0x00000004

//TYPE
#define T_MUX_PERF (LOG_STRUCT_B | LOG_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0007)
//CODES
#define P_MUX_TOTAL_TX_PER_SEC              0x00000001
#define P_MUX_TOTAL_RX_PER_SEC              0x00000002

//TYPE
#define T_PROXYMNGR_PERF (LOG_STRUCT_B | LOG_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PPE | 0x0008)
//CODES




//!!!PROXY LEVEL
//TYPE
#define T_PROXY_STATUS (LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_PROXY | 0x0000)
//CODES
#define E_PORTPLEX_CONNECTED 			0x00000001
#define E_PORTPLEX_DISCONNECTED 		0x00000002
#define E_NODE_SHUTDOWN					0x00000003


//!!!MIDDLEWARE LEVEL
//TYPE - middleware status
#define T_MW_STATUS 		(LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0000)
//CODES

//TYPE - runtime status
#define T_RUNTIME_STATUS 	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0001)
//CODES
#define E_NEW_RUNTIME_CREATED			0x00000001
#define E_RUNTIME_REMOVED				0x00000002

//CODES

//TYPE - runtime warning
#define T_RUNTIME_WARNING 	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0002)
//CODES
#define E_NO_SPACE_FOR_NEW_RUNTIME					0x00000001
#define E_RUNTIME_ALREADY_EXISTING					0x00000002
#define E_UNABLE_TO_READ_DATA_SECTION				0x00000003
#define E_TRIED_TO_REMOVE_NON_EXISTING_RUNTIME		0x00000004
#define E_AGENT_SUSPEND_FAIL						0x00000005
#define E_UNABLE_TO_RESUME_AGENT					0x00000006
#define E_UNABLE_TO_SAVE_RUNTIME_STATE				0x00000007
#define E_UNABLE_TO_RESTORE_RUNTIME_STATE			0x00000008
#define E_NO_RUNTIME_STRUCTURES_FOR_AGENT			0x00000009
#define E_CONTEXT_CHANGE_FAIL						0x0000000A
#define E_AGENT_FAILED								0x0000000B
#define E_EVENT_DELAYED 							0x0000000C
#define E_VM_DATA_MEMORY_INVALID_ACCESS				0x0000000D
#define E_VM_CODE_MEMORY_INVALID_ACCESS				0x0000000E
#define E_VM_INVALID_PRIMITIVE_CALLED				0x0000000F


//TYPE - runtime error
#define T_RUNTIME_ERROR 	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_MW | 0x0003)
//CODES

//TYPE - runtime performance indicator
#define T_RUNTIME_PERF 		(LOG_STRUCT_F | LOG_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0004)
//CODES
#define P_NON_GEN_EVENT_DELAY			0x00000001
#define P_NON_GEN_INSTRUCTION_DELAY		0x00000002

//TYPE - sub-pobicos status
#define T_SP_STATUS 		(LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0005)
//CODES
#define E_SPN_REGISTRATION 				0x00000001
#define E_SPN_DEREGISTRATION			0x00000002
#define E_NODE_DESCRIPTOR_RECEIVED 		0x00000003

//TYPE - middleware warning
#define T_MW_WARNING 		(LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_MEDIUM | LOG_LEVEL_MW | 0x0006)
//CODES

//TYPE - middleware error
#define T_MW_ERROR 			(LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_MW | 0x0007)
//CODES

//TYPE - event execution
#define T_RUNTIME_EH_START		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0008)
#define T_RUNTIME_EH_STOP		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0009)
#define T_RUNTIME_ET_START		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x000A)
#define T_RUNTIME_ET_CONT		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x000B)
#define T_RUNTIME_ET_END		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x000C)
//CODES

//TYPE Agent manager status
#define T_AGENT_MANAGER_STATUS	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x000D)
//CODES

//TYPE Agent manager warning
#define T_AGENT_MANAGER_WARNING	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_MEDIUM | LOG_LEVEL_MW | 0x000E)
//CODES

//TYPE Agent manager error
#define T_AGENT_MANAGER_ERROR	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_MW | 0x000F)
//CODES

//TYPE sub-pobicos error
#define T_SP_ERROR				(LOG_STRUCT_C | LOG_NO_INDICATOR | LOG_PRIORITY_HIGH | LOG_LEVEL_MW | 0x0010)
//CODES
#define E_NODE_DESCRIPTOR_INVALID			0x00000001
#define E_UNKNOWN_RESULT					0x00000002
#define E_SPN_NOT_RESPONDING				0x00000003

//TYPE sub-pobicos performance
#define T_SP_PERF				(LOG_STRUCT_C | LOG_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_MW | 0x0011)
//CODES
#define P_PING_PONG							0x00000001


//!!!API LEVEL
#define T_NON_GEN_EVENT_SIGNAL 		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_API | 0x0000)
#define T_GEN_EVENT_SIGNAL 			(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_API | 0x0001)
#define T_NON_GEN_INSTRUCTION_CALL 	(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_API | 0x0002)
#define T_GEN_INSTRUCTION_CALL 		(LOG_STRUCT_F | LOG_NO_INDICATOR | LOG_PRIORITY_LOW | LOG_LEVEL_API | 0x0003)



#endif
